create event
bildvitta/quasar-app-extension-hub pull request #13
Opened 2021-08-12 17:27 UTC by eliasassuncao

2021-08-12 18:50 UTC, caiotarifa requested changes

2021-08-12 18:50 UTC, caiotarifa commented on src/boot/auth.js
> +    const eventsSent = { token: false }
Não entendi muito bem isso aqui, pode explicar?

2021-08-16 13:11 UTC, plowzzer approved these changes

2021-08-17 17:17 UTC, eliasassuncao commented on src/boot/auth.js
> +    const eventsSent = { token: false }
alinhado via call

2021-08-17 17:22 UTC, caiotarifa approved these changes

2021-08-17 17:23 UTC, plowzzer approved these changes

2021-08-17 18:00 UTC, merged